sudo: required
services:
  - docker

before_install:
  - docker build -t rafpaal/docker-react-tutorial -f Dockerfile.dev .

script:
  - docker run rafpaal/docker-react-tutorial -e CI=true npm run test

