sudo: required
services:
  - docker

before_install:
  - docker build -t rafpaal/docker-react-tutorial -f Dockerfile.dev .

script:
  - docker run rafpaal/docker-react-tutorial -e CI=true npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-rafa-tutorial"
  env: "DockerRafaTutorial-env"
  bucket_name: "elasticbeanstalk-us-east-2-445822713320"
  bucket_path: "docker-rafa-tutorial"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY